export const RECEIVE_MOVIES_REQUEST = 'RECEIVE_MOVIES_REQUEST';
export const RECEIVE_MOVIES_SUCCESS = 'RECEIVE_MOVIES_SUCCESS';
export const RECEIVE_MOVIES_ERROR = 'RECEIVE_MOVIES_ERROR';

export const CHANGE_MOVIE_TITLE_REQUEST = 'CHANGE_MOVIE_TITLE_REQUEST';
export const CHANGE_MOVIE_TITLE_SUCCESS = 'CHANGE_MOVIE_TITLE_SUCCESS';

export const CHANGE_MOVIE_YEAR_REQUEST = 'CHANGE_MOVIE_YEAR_REQUEST';
export const CHANGE_MOVIE_YEAR_SUCCESS = 'CHANGE_MOVIE_YEAR_SUCCESS';
